### ISSUE TITLE
[1.4] Preview/Export button not clickable

### ISSUE THREAD

**Issue by markknol** [tconkling/flump#141]
I just downloaded Flump 1.4 but for some reason I cannot click the preview/export buttons because they are aligned under the grid.

![image](https://cloud.githubusercontent.com/assets/576184/7370095/e43698ca-edb7-11e4-8eb4-6debeacdbe35.png)

**Comment by tconkling** [comment]
Strange! It's working properly on the Mac. Are you using the latest AIR?

**Comment by markknol** [comment]
Thanks for your feedback. No, Ill update to latest AIR and let you know.
