### ISSUE TITLE
[1.4] Export buttons not clickable

### ISSUE THREAD

**Issue by teodorjakobsson** [tconkling/flump#142]
This is not the same issue as the previous post #141, but rather the export buttons (combined, single) stay grayed out even after the assets have been loaded. I just upgraded to 1.4 as I was hoping to try out the combine feature and created a new flump project in the parent directory.
![ps](https://cloud.githubusercontent.com/assets/6860533/7388569/898ea796-ee66-11e4-8c66-2f82d1775c40.png)

**Comment by tconkling** [comment]
Hi Teodor - it looks like the FLAs aren't being fully loaded here. The
'...' in the Modified column appears until loading is complete, at which
point it changes to say either 'Yes' or nothing. The export buttons are
disabled until loading is complete.

I haven't seen this happen before, but I'm guessing that an uncaught error
is being thrown during the loading process (loading errors should be caught
and displayed in the bottom tree), and it's never completing. Are you able
to narrow down what is happening here? Does it happen with the example
Flump project? Is there a subset of FLAs in this project that does or does
not exhibit the problem?

**Comment by tconkling** [comment]
(Also, are you able to run Flump through adl to see if there's an error
being thrown? This is a bit of a pain to set up if you're not already
building Flump from source, so no worries if not.)

**Comment by tconkling** [comment]
Hey @teodorjakobsson - I just encountered this issue in my own project and pushed a fix. Can you try the latest exporter (1.4.1): https://github.com/tconkling/flump/releases/download/1.4.1/flump-exporter.air and see if it fixes your issue?

**Comment by teodorjakobsson** [comment]
Hi, sorry for the late followup but I can confirm that trying to merge project FLAs with different frame rates was the culprit in my case. Went through each FLA and made sure they used the same frame rate and now the exporter works as intended (1.4.0), also updated to the new version which results in a more informative error (1.4.1). Thanks for the help.
