### ISSUE TITLE
Starling 2.0 

### ISSUE THREAD

**Issue by marchbold** [tconkling/flump#146]
We've recently updated to the latest version of Starling and have discovered an issue with the Flump runtime lib. The new framework no longer uses `Starling.handleLostContext` so this library is destroying bitmap assets that need to be retained.

As a short term workaround we have simply removed the clear/dispose calls in the `Loader` class:
- [Loader:L119-L121](../blob/master/runtime/src/main/as/flump/display/Loader.as#L119-L121)
- [Loader:L132-L134](../blob/master/runtime/src/main/as/flump/display/Loader.as#L132-L134)

So far this seems to be working, but just wanted to inform you of the issue.

**Comment by tconkling** [comment]
Thanks for the heads up! I haven't updated to Starling 2.0 yet, but I'm planning on doing it soon, at which point I'll be taking a look at this issue.

**Comment by tconkling** [comment]
(Fixed a while back.)

**Comment by marchbold** [comment]
Thanks for letting me know, will update our app in the next release.
