### ISSUE TITLE
Trying to compile exporter project

### ISSUE THREAD

**Issue by mathieuanthoine** [tconkling/flump#147]
Hi,

I try to compile the exporter project with Flash Builder and get two unknow errors:

- configuration variable ‘compiler.library-path’ value contains the unknown token M2_REPO
- the -init-ooo target doesn't exist in this project (build.xml / line 19)

A little help would be appreciated :)

**Comment by tconkling** [comment]
The `M2_REPO` path variable should be set to your local maven repository directory (on Mac, it's `~/.m2/repository`). There should be a place in the Flash Builder preferences to set path variables.

Re: the `-init-ooo` target - that's part of the `ant` command line build and doesn't have anything to do with a Flash Builder project; is Flash Builder trying to construct a project from the ant build script or something?

**Comment by mathieuanthoine** [comment]
Thanks for explanations. In fact the https://github.com/tconkling/maven-repo was missing

**Comment by tconkling** [comment]
It sounds like Flash Builder's ant importer doesn't handle complex build scripts. (The `prepare` target is contained in another build script that's downloaded by build.xml). Are you on a Mac? Can you try running `ant` from the command line?

**Comment by mathieuanthoine** [comment]
At this point I don't have ant installed, I have just launched the Flump-exporter project in Flash Builder.
Is there something to know before installing Ant, a special configuration in Flash Builder to have ?
PS: I'm on Windows 10 (on a Mac ;))

**Comment by tconkling** [comment]
(Sorry for slow response, I've been away) - for ant, you'll need to install Java first. The instructions on the web page (http://ant.apache.org/manual/install.html) should get you where you need!

**Comment by mathieuanthoine** [comment]
Hi, some news about compilation.
It's ok now, I can compile the exporter and have the flump-exporter.swf file generated in the dist but:

flump-exporter.swf doesn't work with Flash player 21 : blank screen
what is the next step to create a .air file ?
is it possible to test the project without these compilation steps ? Do you use Flash Builder to develop flump exporter ? Can you compile directly from Flash Builder and can you test flump in Flash Builder IDE ?
Thank you for your help

**Comment by tconkling** [comment]
If you run the `package` target in the exporter's ant file, it will create the .air for you. You can examine the target to see how it works: it's using the `adt` tool to produce an AIR package.

Re: Flash Builder - I use IntelliJ IDEA, but it's definitely possible to use Flash Builder as well! You want to look at its support for packaging AIR files. I don't remember exactly what's required, as I no longer use that IDE, but it's easily accomplished.

**Comment by mathieuanthoine** [comment]
thank you, I can generate .air file and now test in FlashDevelop with adl !

**Comment by tconkling** [comment]
Glad to hear it!
