### ISSUE TITLE
Error: Unable to parse movie in <MovieClip name>

### ISSUE THREAD

**Issue by Joncom** [tconkling/flump#167]
Got this vague error message and spent a fair amount of time trying to figure out what it meant.

Turns out that a MovieClip which contains a layer with no name (ie. empty string) will cause this.

On the one hand, it's probably wise to name all layers.

On the other hand, it would sure by nice if the error message had been a little more specific.

**Comment by tconkling** [comment]
Thanks for the report! This is fixed in 6a69c89.

**Comment by Joncom** [comment]
Cool! ^^
