### ISSUE TITLE
Ported to Haxe (Starling + OpenFL) version of Flump

### ISSUE THREAD

**Issue by CrazyFlasher** [tconkling/flump#172]
Runtime with sample:
https://github.com/CrazyFlasher/flump-hx

Ported from my fork:
https://github.com/CrazyFlasher/flump

Supports this feature, that hasn't been merged to master branch, however is very useful to support multiple assets qualities:
https://github.com/tconkling/flump/pull/164

**Comment by tconkling** [comment]
Thanks! I added your link to the [README](https://github.com/tconkling/flump/blob/master/README.md)
