### ISSUE TITLE
No rotation?

### ISSUE THREAD

**Issue by dionjwa** [tconkling/flump#4]
It looks like the new flump version does not have rotation values exported.

**Comment by sixFingers** [comment]
I still can't get my head around this. I need to feed my function a rotation + shearX and Y values in _scalar_, not _radians_. At the moment rotation works fine but can't make skewing working for it (the clip "attack" of the demo for example). I understand that if skewX == skewY then rotation = skewX. But in case they're different? I miss this for a Love2D runtime i'm writing (everything else is done)

**Comment by SimianLogic** [comment]
Not all engines expose a shear/skew or transform matrix. We've used Flump with Futile for Unity and SpriteKit for iOS (Neither supports it out of the box). We imposed a restriction on our animators that skewing was not allowed, but there's not a super easy way to do that in Flash... We ended up rewriting the Sprite class in Futile and haven't needed to figure out a solution for SpriteKit yet.

**Comment by sixFingers** [comment]
@SimianLogic i'm impressed (negatively), even the webgl demos seems to support it (well, after you have constructed a correct matrix). Actually Love2D supports shearing, the point is, i don't know how to read / use those two radians values coming out from Flump (in case the two are different).

**Comment by tconkling** [comment]
@sixFingers - i'm not sure what you mean by needing to express the skew values in scalar? 

Regardless - Starling (the as3 framework that the Flump reference implementation is implemented in) has an example of how to construct a skew transform: https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/utils/MatrixUtil.as. Can you pass Love2D a transform matrix that you've constructed?

**Comment by sixFingers** [comment]
@tconkling - yes, sounds strange. The parameters required for my function are scalar values (skewX, skewY) from -1 to 1. 

Regardless - thanks a lot. I dug for a while, but totally skipped the code you're pointing me at.

**Comment by tconkling** [comment]
Huh - without looking at the code, I would *guess* that you could transform our radians values (from 0-2PI) to their expected values by doing `(skew <= PI ? skew / PI : (skew - 2PI) / PI`.

**Comment by sixFingers** [comment]
Yes, i wasn't too clear, that was exactly my first attempt, but couldn't get correct results. At this point it's more a Love2D matter, since i tried out a trivial webgl implementation just to check my math, and everything worked pretty easily. I'll try a second attempt, maybe the first wasn't correct on my side.

**Comment by sixFingers** [comment]
@tconkling I tried hard, but couldn't solve the skew the end. 
Nonetheless, I have published my LOVE2D runtime for Flump, it supports everything apart from that _skewwwww_ thing. 
If interested in listing it in the "Runtimes" chapter, here's the [public repo](https://github.com/sixFingers/lump). Thanks!

**Comment by tconkling** [comment]
Cool, I'll add a link!
