### ISSUE TITLE
Feature Request: Masking

### ISSUE THREAD

**Issue by jwillmann** [tconkling/flump#43]
Is it possible to support Flash's masking in Flump?

**Comment by SoleilSmile** [comment]
What about support for masking MoveClips in the future? Animation effects are really limited without the ability to mask.

**Comment by tconkling** [comment]
Hey SoleilSmile - it's possible, though it's unlikely to happen unless somebody who needs the feature also implements it, as it's a non-trivial amount of work.

However, with Starling's recent support of the stencil buffer it may be a bit easier to implement now than when we began on Flump a few years ago.

**Comment by timmutton** [comment]
were there ever any updates on this?
