### ISSUE TITLE
Skew in Flash CS5.5

### ISSUE THREAD

**Issue by dionjwa** [tconkling/flump#6]
There seems to be a discrepancy between Flash's skew values and actual 2D affine skew transforms.  To illustrate this:
- create square symbol, and add it to the stage
- set the pivot to the lower right of the symbol.
- skew it by dragging the y axis 'skew' value in the 'transform' box.

You'll notice that the shape is skewed, but also rotates/scales around the pivot when the degrees > 90.  If you take the transform values (via flump) and apply them to shape (we did this in opengl), it will look different, because only skew values are exported, not rotation or scale values.  I.e. there is only shear, so e.g. the shape cannot be visually to the right of its pivot point with only y skew.

Somehow, Flash is combining skew and (rotation or scale) visually in Flash, but the exported matrix only has skew values.  At least, that's as far as I am with this problem so far.

I believed this worked better in a previous version of Flump where rotation values were exported directly.  A similar problem occurred, but I worked around this by taking the scale into account, and adjusting the radians.

**Comment by jackwlee01** [comment]
I think I have just encountered this same issue, it is present in the preview of the exporter. I have put the project here for you to see: http://www.filedropper.com/skewbug

Note that on frame 41 I shifted the pivot.
